documentation:
  - changed-files:
    - '**/*.md'

ci/cd:
  - changed-files:
    - '.github/actions/**/*.yml'
    - '.github/workflows/**/*.yml'

backend:
  - changed-files:
    - '**/*.h'
    - '**/*.cpp'
    - '**/*.cmake'
    - '**/CMakeLists.txt'

frontend:
  - changed-files:
    - '**/*.py'

'unit test':
  - changed-files:
    - 'test/**/*'
