# Defined in torch_backend/csrc/Module.cpp

# Defined in torch_backend/csrc/backend/init.cpp
def _init(): ...


# Defined in torch_backend/csrc/backend/Lock.cpp
def _lock_mutex(): ...
def _unlock_mutex(): ...


# Defined in torch_backend/csrc/backend/device.cpp
def _synchronize(): ...
def _setDevice(device: int): ...
def _getDevice() -> int: ...
def _getDeviceCount() -> int: ...
def _canDeviceAccessPeer(device_id: int, peer_device_id: int) -> bool: ...
