name: Pull Request Labeler

on: pull_request_target

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - name: Label the PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
